# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Brett Wickham
email: brett.wickham@gmail.com
description: >
  Web Developer
# baseurl: "/blog"
url: "http://brettwickham.com"

github_url: https://github.com/brettwickham/
linked_url: https://www.linkedin.com/in/brett-wickham/
facebook_url: https://www.facebook.com/brettwick86
twitter_url: https://mobile.twitter.com/brettwick86

# Custom collections
collections:
  projects:
    # output: true

# Build settings
markdown: kramdown
# theme: minima
# sass:
#    sass_dir: assets/styles
plugins:
  # - jekyll-feed

# Custom permalinks
permalink: pretty

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - webpack/
  - node_modules/
  - npm-debug.log
  - package.json
  - webpack.config.json
#   - Gemfile
#   - Gemfile.lock
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
